### ISSUE TITLE
Create Jenkins instance to start running builds

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-bridge#10]
@Emily-Jiang please investigate, now that Adam moved the initial TCK test, it can be useful to have snapshot artifacts available

**Comment by Emily-Jiang** [comment]
@sberyozkin [here](https://github.com/eclipse/microprofile-build-infra/pull/10) has the change. Once it is merged in, you can run the Jenkins release build.

**Comment by sberyozkin** [comment]
@Emily-Jiang Great stuff, thanks :+1: . We can close this issue now.
@ayoho FYI too
