### ISSUE TITLE
Decide on the API package name

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-bridge#15]
Right now, so far in TCK only, we have packages starting from `org.eclipse.microprofile.jwt.bridge.*` and we'll have to add API classes too.

Question, can `org.eclipse.microprofile.jwt.bridge.*` be problematic in OSGI aware containers given that MP JWT Auth API has the `org.eclipse.microprofile.jwt` package, ex, for `JsonWebToken` ?

Should we settle on something like `org.eclipse.microprofile.jwtbridge.* ` ?

**Comment by Emily-Jiang** [comment]
`org.eclipse.microprofile.jwt.bridge.*` is good.

**Comment by Emily-Jiang** [comment]
ideally, `JsonWebToken` should be in the package of `org.eclipse.microprofile.jwt.auth.*`, but we have to leave with the current package name now.
