### ISSUE TITLE
Move optional Jakarta specific MP JWT spec content to JWT bridge spec doc

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-bridge#4]
@dblevins @ayoho Can you please look into it ? I can help with the PR, is it what we want to move, 

https://github.com/eclipse/microprofile-jwt-auth/blob/main/spec/src/main/asciidoc/interoperability.asciidoc#recommendations-for-optional-container-integration
?

Also CC @starksm64

**Comment by sberyozkin** [comment]
I'll give this one a try

**Comment by ayoho** [comment]
@sberyozkin Sorry for the delay. I think that's a sensible section to move over, yes. I'm happy to do this as well if you haven't gotten to it yet.

**Comment by sberyozkin** [comment]
Hi Adam, please go ahead with this one when you get a chance, I'll look at #13

**Comment by sberyozkin** [comment]
Closed by #14
