### ISSUE TITLE
Rename repository to microprofile-jwt-bridge

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-bridge#6]
@Emily-Jiang What do you think ? Would it look like a more typical repository name ? I've no any strong opinion about it, will let you decide, if agreed, please update the root pom after #1 is merged, cheers

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang What do you think ? Would it look like a more typical repository name ? I've no any strong opinion about it, will let you decide, if agreed, please update the root pom after #1 is merged, cheers

microprofile-jwt-bridge looks good and it is consistent with the microprofile-jwt-auth. I will ask EMO to update this.

**Comment by Emily-Jiang** [comment]
[Here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3646) is the issue for the name update.

**Comment by Emily-Jiang** [comment]
All done!

**Comment by sberyozkin** [comment]
Thanks Emily
