### ISSUE TITLE
Fix Repository `About` description

### ISSUE THREAD

**Issue by sberyozkin** [eclipse/microprofile-jwt-bridge#9]
https://github.com/eclipse/microprofile-jwt-bridge `About` still says `microprofile-jwtBridge`.

@Emily-Jiang, please have a look

**Comment by Emily-Jiang** [comment]
Added a comment [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3646)

**Comment by Emily-Jiang** [comment]
All done @sberyozkin @ayoho

**Comment by sberyozkin** [comment]
Thanks @Emily-Jiang for looking after it :+1:

**Comment by Emily-Jiang** [comment]
> Thanks @Emily-Jiang for looking after it 👍

@sberyozkin my pleasure!
